# Julia 變數 (Variables)、常數 (Constants) 與內建數學常數、與運算

## 1. 變數

變數的宣告和指定變數值

In [2]:
x = 10

10

也可以宣告字串變數，字串會在後續的內容中詳細介紹。

In [3]:
s = "Hello Julia"

"Hello Julia"

宣告 x 和 y，並將值均指定為 3。

In [4]:
x = y = 3

3

Unicode 字元做為變數名稱，以 θ 宇元為例，輸入的方法是：\theta[tab]，就可以轉變為 Unicode 字元。

In [5]:
θ = 2

2

## 2. 常數

In [6]:
const z = 10

10

**(!) 下例要注意的地方是，m 會是常數，而 n 不是。**

In [7]:
const m = n = 3

3

在 Julia 中，常數的值是可以改變的，但是會有 WARNING 訊息。

In [8]:
m = 2

2

**(!) 若用已存在的變數名稱來宣告常數，會產生 error。**

In [9]:
const x = 3

ErrorException: cannot declare x constant; it already has a value

declaring constant fixes the type

In [12]:
const x1 = 1
typeof(x1)

Int64

In [13]:
x1 = 2.7

ErrorException: invalid redefinition of constant x1

> 1. constant seems to be **global** and performance will be improved. (check required)

### 內建數學常數

Julia 內建許多數學常數，部分常數也可以透過 Unicode 字元數學符號來使用。

#### 圓周率 $\pi$

In [14]:
Base.MathConstants.pi

π = 3.1415926535897...

或是輸入 \pi[tab]

In [15]:
π

π = 3.1415926535897...

或是直接用 pi

In [16]:
pi

π = 3.1415926535897...

#### 歐拉數 (Euler's number)

In [17]:
Base.MathConstants.e

ℯ = 2.7182818284590...

或是輸入 \euler[tab]

In [18]:
ℯ

ℯ = 2.7182818284590...

#### 卡塔蘭常數

In [19]:
Base.MathConstants.catalan

catalan = 0.9159655941772...

#### 歐拉常數（Euler-Mascheroni constant)

In [20]:
Base.MathConstants.eulergamma

γ = 0.5772156649015...

#### 黃金比例

In [21]:
Base.MathConstants.golden

φ = 1.6180339887498...

## 3. 運算

### 3.1 運算子

常用運算子可分為下列幾種類型：
- 算術運算子
- 位元運算子
- 指定/更新運算子
- 比較運算子
- 點運算

詳細的運算子請參考文件及投影片說明。

Julia 運算子就是函式，例如加法。

In [1]:
a = 1
b = 2

a + b

3

也可以用函式方式來進行加法。

In [23]:
+(a, b)

3

同樣的，部分運算子也可以用相對應的 Unicode 字元來做運算。例如相除取整數，輸入 \div[tab]。

In [24]:
a ÷ b

0

或是

In [ ]:
÷(a, b)

或是也可以使用 `div()` 函式。

In [ ]:
div(a, b)

÷ seems to be python's 'floor division'

In [28]:
(1.9*3) ÷ 3

1.0

下面範例是 bitwise XOR，輸入 \xor[tab]
> XOR: if the two bits are the same, return false; different, true.

In [30]:
c = 0001
d = 1010

c ⊻ d

1011

另外，有一些運算子也另有相對應的函式可以呼叫，結果都是相同的。以 == 為例：

In [31]:
a == b

false

In [32]:
==(a, b)

false

In [33]:
# 也可以用 isequal()
isequal(a, b)

false

**triple equals `===`**
- `x === y` is true when two objects are programmatically indistinguishable – i.e. you cannot write code that demonstrates any difference between x and y.
- https://stackoverflow.com/questions/38601141/what-is-the-difference-between-and-comparison-operators-in-julia

In [10]:
1.0 === 1 

false

In [11]:
1.0 == 1

true

In [13]:
-0.0 === 0.0

false

In [14]:
-0.0 == 0.0

true

#### 點運算 (Dot Operation)

對於一維陣列 (向量) 來說，點運算是很方便可以用來運算的方式。例如說我們要對向量中的每一個元素進行平方，用 `.^ 2` 就可以。

下面例子是兩種不同的寫法是用運算子和函式表達，結果均相同。點運算進行了**”廣播” (broadcast)**的運算完成對陣列每個元素平方的運算。

有關於陣列及其運算，在未來的內容裡會有更詳細的介紹。

In [34]:
a = [1, 2, 3]
b = 2

2

In [35]:
a .^ b

3-element Array{Int64,1}:
 1
 4
 9

In [36]:
# 或
(^).(a, b)

3-element Array{Int64,1}:
 1
 4
 9

### 3.2 常用運算函式

#### 3.2.1 常用 Rounding 函式

|函式|說明|
|---|---|
|`round(x)`|round 至最近的整數|
|`floor(x)`|往 -Inf round 至最近的整數|
|`ceil(x)`|往 Inf round 至最近的整數|
|`trunc(x)`|往 0 round 至最近的整數|

在先前的內容中曾詳細介紹 `round()` 函式及不同的 `round()` 方式，有需要的話可以參考**Julia 數值系統介紹**內容，今天的範例就不重複。

在 Rounding 的方法部分，Julia 是採用 IEEE 754 規範，也就是 `RoundNearest`，取最近的偶數(四捨五取最近偶數)，而非我們一般講的四捨五入。

要採用不同的 rounding 方法，可在呼叫 `round()` 函式時加入不同的常數參數，列表如下:

|常數|描述|
|---|---|
|RoundNearest (default)|四捨五取最近偶數(預設)|
|RoundNearestTiesAway|四捨五取遠離0|
|RoundNearestTiesUp|四捨五入|
|RoundToZero|無條件捨去|
|RoundFromZero (BigFloat only)|四捨五取遠離0|
|RoundUp|無條件進位|
|RoundDown|無條件退位|

`floor()` 函式是往 `-Inf` 捨至最接近的整數。

In [37]:
floor(2.3)

2.0

In [38]:
floor(-2.3)

-3.0

`ceil()` 函式是往 `Inf` 進至最接近的整數。

In [39]:
ceil(2.3)

3.0

In [40]:
ceil(-2.3)

-2.0

`trunc()` 函式是往 0 round 至最接近的整數。

In [41]:
trunc(-2.3)

-2.0

#### 3.2.2 常用 Division 函式

|函式|說明|
|---|---|
|`div(x,y)`, `x÷y`|相除取整數|
|`fld(x,y)`|相除向 -Inf 取整數|
|`cld(x,y)`|相除向 +Inf 取整數 |
|`rem(x,y)`|餘數|
|`mod(x,y)`|同餘|
|`divrem(x,y)`|回傳 `div(x,y)` 與 `rem(x,y)`|
|`fldmod(x,y)`|回傳 `fld(x,y)` 與 `mod(x,y)`|
|`gcd(x, y)`|最大公因數|
|`lcm(x, y)`|最小公倍數|

> `mod()` and `rem()` gives identical results in the positive case. 

> `mod()` is computed by `x - y*floor(x/y)`;
> `rem()` directly calls `rem_float`

In [47]:
mod(0.95,0.01) == rem(0.95,0.01)

true

In [48]:
7.3 ÷ 5.5

1.0

In [49]:
fld(-7.3,5.5)

-2.0

In [50]:
cld(5.5,2.2)

3.0

In [51]:
rem(15, 4)

3

**(?) what does 0:2 for?**

In [5]:
collect(0:2)

3-element Array{Int64,1}:
 0
 1
 2

In [8]:
mod(3,2)

1

`mod(x::Integer, r::AbstractUnitRange)`
- Find y in the range r such that xy(modn), where n = length(r), i.e. y = mod(x - first(r), n) + first(r).

In [2]:
mod(3, 0:2)

0

In [3]:
divrem(15, 4)

(3, 3)

In [61]:
fldmod(7.3,5.5)

(1.0, 1.7999999999999998)

In [62]:
gcd(30, 12)

6

In [63]:
lcm(30, 12)

60

#### 3.2.3 常用正負號與絕對值函式

|函式|說明|
|---|---|
|`abs(x)`|絕對值|
|`abs2(x)`|絕對值平方|
|`sign(x)`|正負號, 回傳 -1 (負號), 0 (x 為 0), or +1 (正號)|
|`signbit(x)`|是否有正負號, 回傳 `true` / `false`|
|`copysign(x,y)`|a value with the magnitude of x and the sign of y|
|`flipsign(x,y)`|a value with the magnitude of x and the sign of x*y|

In [64]:
abs(-3)

3

In [65]:
abs2(-3)

9

In [66]:
sign(-3)

-1

In [67]:
sign(0)

0

In [68]:
# UInt 是沒有正負號的, 所以回傳值為 false
signbit(UInt(3))

false

In [72]:
signbit(Int(3))

false

In [73]:
signbit(Int(-3))

true

In [76]:
copysign(-3, 2) # sign(2)*abs(-3)

3

In [77]:
flipsign(-3, -2) # sign(-3*-2)*abs(-3)

3

#### 3.2.4 常用 Powers, logs and roots 函式

|函式|說明|
|---|---|
|`sqrt(x)`, `√x`|平方根|
|`cbrt(x)`, `∛x`|立方根|
|`hypot(x,y)`|直角三角形求斜邊長 (`hypot` for *hypotenuse*)|
|`exp(x)`|自然指數函式 (natural exponential function), 即 $e^x$|
|`exp2(x)`|$2^x$|
|`exp10(x)`|$10^x$|
|`log(x)`|$log x$ (i.e. natural log $\ln x$)|
|`log(b,x)`|$log_b x$|
|`log2(x)`|$log_2 x$|
|`log10(x)`|$log_{10} x$|

> type `\sqrt` + `[tab]` to get `√`

In [79]:
println(sqrt(4))
println(√16)

2.0
4.0


In [80]:
println(cbrt(8))
println(∛27)

2.0
3.0


In [81]:
hypot(12, 5)

13.0

In [82]:
exp(1)

2.718281828459045

In [83]:
log(10)

2.302585092994046

In [89]:
log(exp(1))

1.0

In [84]:
log(2, 4)

2.0

In [85]:
log2(4)

2.0

In [86]:
log10(100)

2.0

#### 3.2.5 常用 三角函數與雙曲函數 (Trigonometric and hyperbolic functions)

使用弧度 (radian) 的三角函數:

|-|-|-|-|-|-|
|---|---|---|---|---|---|
|sin    |cos|    tan    |cot|    sec|    csc|
|sinh  | cosh|   tanh  | coth|   sech|   csch|
|asin |  acos |  atan  | acot |  asec |  acsc|
|asinh|  acosh | atanh|  acoth | asech | acsch|
|sinc|   cosc  |sinpi|  cospi|

使用角度 (degree) 的三角函數:

|-|-|-|-|-|-|
|---|---|---|---|---|---|
|sind|   cosd|   tand|   cotd|   secd|   cscd|
|asind|  acosd|  atand|  acotd|  asecd|  acscd|

# others

## double colon `::`

In [12]:
? Vector

search: Vector BitVector DenseVector StridedVector AbstractVector



```
Vector{T} <: AbstractVector{T}
```

One-dimensional dense array with elements of type `T`, often used to represent a mathematical vector. Alias for [`Array{T,1}`](@ref).

---

```
Vector{T}(undef, n)
```

Construct an uninitialized [`Vector{T}`](@ref) of length `n`. See [`undef`](@ref).

# Examples

```julia-repl
julia> Vector{Float64}(undef, 3)
3-element Array{Float64,1}:
 6.90966e-310
 6.90966e-310
 6.90966e-310
```

---

```
Vector{T}(nothing, m)
```

Construct a [`Vector{T}`](@ref) of length `m`, initialized with [`nothing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Nothing <: T`.

# Examples

```jldoctest
julia> Vector{Union{Nothing, String}}(nothing, 2)
2-element Array{Union{Nothing, String},1}:
 nothing
 nothing
```

---

```
Vector{T}(missing, m)
```

Construct a [`Vector{T}`](@ref) of length `m`, initialized with [`missing`](@ref) entries. Element type `T` must be able to hold these values, i.e. `Missing <: T`.

# Examples

```jldoctest
julia> Vector{Union{Missing, String}}(missing, 2)
2-element Array{Union{Missing, String},1}:
 missing
 missing
```


In [10]:
Vector{Float64}

Array{Float64,1}

In [13]:
dump(Vector{Int})

Array{Int64,1} <: DenseArray{Int64,1}


In [11]:
function foo(x)
    y::Float64 = x
    y # this is required!
end
z = 1
(typeof(z), foo(z),typeof(foo(z)))

(Int64, 1.0, Float64)

In [22]:
function bar(x::Int64, y::Int64)::Float64 # input Int64, Int64; output Int64
    x + y
end
bar(1,2)

3.0

In [23]:
bar(1.0,2.0) # error occurs because of the type of inputargument do not match

MethodError: MethodError: no method matching bar(::Float64, ::Float64)

In [24]:
y::Float64

UndefVarError: UndefVarError: y not defined

In [25]:
y = 1
y::Float64

TypeError: TypeError: in typeassert, expected Float64, got Int64

In [26]:
y::Int64

1

# Other
## Help

In [1]:
? fill # show me help of a function

search: fill fill! finally findall filter filter! filesize filemode isfile



```
fill(x, dims)
```

Create an array filled with the value `x`. For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with each element initialized to `1.0`.

# Examples

```jldoctest
julia> fill(1.0, (5,5))
5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
```

If `x` is an object reference, all elements will refer to the same object. `fill(Foo(), dims)` will return an array filled with the result of evaluating `Foo()` once.


In [2]:
? Number # show me help of a certain type

search: Number LineNumberNode VersionNumber



```
Number
```

Abstract supertype for all number types.


In [3]:
? Int64

search: Int64 UInt64 Int16 UInt16



```
Int64 <: Signed
```

64-bit signed integer type.


In [4]:
? Type

search: Type typeof TypeVar typemin typemax TypeError typejoin typeassert



No documentation found.

`Core.Type` is of type `UnionAll`.

# Summary

```
struct UnionAll <: Type{T}
```

# Fields

```
var  :: TypeVar
body :: Any
```

# Supertype Hierarchy

```
UnionAll <: Type{T} <: Any
```


In [5]:
? DataType

search: DataType



No documentation found.

# Summary

```
mutable struct DataType <: Type{T}
```

# Fields

```
name             :: Core.TypeName
super            :: DataType
parameters       :: Core.SimpleVector
types            :: Core.SimpleVector
names            :: Core.SimpleVector
instance         :: Any
layout           :: Ptr{Nothing}
size             :: Int32
ninitialized     :: Int32
uid              :: Int32
abstract         :: Bool
mutable          :: Bool
hasfreetypevars  :: Bool
isconcretetype   :: Bool
isdispatchtuple  :: Bool
isbitstype       :: Bool
zeroinit         :: Bool
isinlinealloc    :: Bool
llvm::StructType :: Ptr{Nothing}
llvm::DIType     :: Ptr{Nothing}
```

# Supertype Hierarchy

```
DataType <: Type{T} <: Any
```


In [6]:
? ∈ # show how to type a character

"∈" can be typed by \in<tab>

search: ∈



```
in(x)
```

Create a function that checks whether its argument is [`in`](@ref) `x`, i.e. a function equivalent to `y -> y in x`.

The returned function is of type `Base.Fix2{typeof(in)}`, which can be used to implement specialized methods.

---

```
in(item, collection) -> Bool
∈(item, collection) -> Bool
∋(collection, item) -> Bool
```

Determine whether an item is in the given collection, in the sense that it is [`==`](@ref) to one of the values generated by iterating over the collection. Returns a `Bool` value, except if `item` is [`missing`](@ref) or `collection` contains `missing` but not `item`, in which case `missing` is returned ([three-valued logic](https://en.wikipedia.org/wiki/Three-valued_logic), matching the behavior of [`any`](@ref) and [`==`](@ref)).

Some collections follow a slightly different definition. For example, [`Set`](@ref)s check whether the item [`isequal`](@ref) to one of the elements. [`Dict`](@ref)s look for `key=>value` pairs, and the key is compared using [`isequal`](@ref). To test for the presence of a key in a dictionary, use [`haskey`](@ref) or `k in keys(dict)`. For these collections, the result is always a `Bool` and never `missing`.

# Examples

```jldoctest
julia> a = 1:3:20
1:3:19

julia> 4 in a
true

julia> 5 in a
false

julia> missing in [1, 2]
missing

julia> 1 in [2, missing]
missing

julia> 1 in [1, missing]
true

julia> missing in Set([1, 2])
false
```


### Symbol

In [1]:
using DataFrames

In [2]:
row2append = Dict(:col2 => "F", :col1 => 2)

Dict{Symbol,Any} with 2 entries:
  :col2 => "F"
  :col1 => 2

In [3]:
df = DataFrame()
df.col1 = 1:5
df.col2 = ["M", "F", "F", missing, "M"]
show(df)
push!(df, row2append)
show(df)

5×2 DataFrame
│ Row │ col1  │ col2    │
│     │ Int64 │ String⍰ │
├─────┼───────┼─────────┤
│ 1   │ 1     │ M       │
│ 2   │ 2     │ F       │
│ 3   │ 3     │ F       │
│ 4   │ 4     │ missing │
│ 5   │ 5     │ M       │6×2 DataFrame
│ Row │ col1  │ col2    │
│     │ Int64 │ String⍰ │
├─────┼───────┼─────────┤
│ 1   │ 1     │ M       │
│ 2   │ 2     │ F       │
│ 3   │ 3     │ F       │
│ 4   │ 4     │ missing │
│ 5   │ 5     │ M       │
│ 6   │ 2     │ F       │

In [4]:
typeof(:col1)

Symbol

In [5]:
df[:,:col1] # use symbol to locate

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 2

In [6]:
df[:,[:col1]] # use symbol to locate

6×1 DataFrame
│ Row │ col1  │
│     │ Int64 │
├─────┼───────┤
│ 1   │ 1     │
│ 2   │ 2     │
│ 3   │ 3     │
│ 4   │ 4     │
│ 5   │ 5     │
│ 6   │ 2     │